name: Loterias Robo Auto (Trator GG-456)

on:
  schedule:
    - cron: '30 0 * * *' # Roda automaticamente às 21:30 (Brasília)
  workflow_dispatch: # Ativa o botão manual na aba Actions

jobs:
  run-trator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Requests
        run: pip install requests
          
      - name: Rodar Motor
        run: python main.py
        env:
          # Conecta os segredos do seu GitHub ao código
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
