name: Loterias Robo Auto (Trator GG-456)

on:
  schedule:
    - cron: '30 0 * * *'
    - cron: '0 1 * * *'
    - cron: '30 2 * * *'
  
  workflow_dispatch:

jobs:
  run-trator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Instalar Dependencias
        run: pip install requests
          
      - name: Acionar Motor GG-456
        run: python main.py
