name: Loterias Robo Auto (Trator GG-456)

on:
  schedule:
    # Atenção: Horários em UTC (GMT+0). Brasil = UTC-3.
    # 00:30 UTC = 21:30 Brasil
    # 01:00 UTC = 22:00 Brasil
    # 02:30 UTC = 23:30 Brasil
    - cron: '30 0 * * *'
    - cron: '0 1 * * *'
    - cron: '30 2 * * *'
  
  # Gatilho manual para você rodar quando quiser no painel "Actions"
  workflow_dispatch:

jobs:
  run-trator:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Instalar Ferramentas Mestre
        run: pip install requests gspread gspread-formatting firebase-admin urllib3
          
      - name: Acionar Motor GG-456
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: python main.py
