name: Robo Loterias Nuvem Blindada

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '0 19 * * *'
    - cron: '0 0 * * *'
    - cron: '0 1 * * *'
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  executar-processamento:
    runs-on: ubuntu-latest
      
    steps:
      - name: Puxar o codigo
        uses: actions/checkout@v4
        
      - name: Configurar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Instalar Dependencias
        run: pip install requests
        
      - name: Rodar o Robo
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python robo.py
